name: "Deploy Pull Request Development Branch"

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy-terraform:
    name: "Terraform Deployments"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=deployments init

      # Had some issues with exit code 3, So I decided to ignore this step (https://github.com/hashicorp/terraform/issues/31543)
      # - name: Terraform Format
      #   run: terraform -chdir=deployments fmt -check

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Terraform Plan
        run: |
          terraform -chdir=deployments plan \
            -input=false \
            -var branch_prefix=Production \
            -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} \
            -var aws_secret_key=${{ secrets.AWS_SECRET_KEY }} \
            -var aws_session_token=${{ secrets.AWS_SESSION_TOKEN }} \

      - name: Terraform Plan
        run: |
          terraform -chdir=deployments apply \
            -auto-approve \
            -input=false \
            -var branch_prefix=Production \
            -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} \
            -var aws_secret_key=${{ secrets.AWS_SECRET_KEY }} \
            -var aws_session_token=${{ secrets.AWS_SESSION_TOKEN }} \
