name: "Deploy Production Branch"

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy-terraform:
    name: "Terraform Deployments"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Get Production State
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.T_TOKEN }}
          name: production-terraform-state
          path: deployments
          if_no_artifact_found: ignore

      - name: Terraform Init
        if: steps.download-artifact.outcome == 'success'
        run: terraform -chdir=deployments init

      - name: Terraform Plan
        run: |
          terraform -chdir=deployments plan \
            -input=false \
            -var branch_prefix=Production \
            -var aws_account_id=${{ secrets.AWS_ACCOUNT_ID }} \
            -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} \
            -var aws_secret_key=${{ secrets.AWS_SECRET_KEY }} \
            -var aws_session_token=${{ secrets.AWS_SESSION_TOKEN }} \

      - name: Terraform Apply
        run: |
          terraform -chdir=deployments apply \
            -auto-approve \
            -input=false \
            -var branch_prefix=Production \
            -var aws_account_id=${{ secrets.AWS_ACCOUNT_ID }} \
            -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} \
            -var aws_secret_key=${{ secrets.AWS_SECRET_KEY }} \
            -var aws_session_token=${{ secrets.AWS_SESSION_TOKEN }} \

      - name: Save Production State
        uses: actions/upload-artifact@v3
        with:
          name: production-terraform-state
          path: deployments/terraform.tfstate
